fix: make number cargo package keywords less than 5 (#124)
Fix

```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): expected at most 5 keywords per crate
```

Signed-off-by: Richard Chien <stdrc@outlook.com>